; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = thmi
boards_dir = boards

[env]
platform = espressif32 @ 6.9.0
framework = arduino
monitor_speed = 115200
upload_speed = 460800
monitor_filters = esp32_exception_decoder
build_type = debug
lib_deps = 
	https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.0
	bblanchon/ArduinoJson @ 6.21.3
	mathertel/OneButton @ 2.0.3

[env:thmi]
board = lilygo-t-hmi
board_build.arduino.memory_type = qio_opi
build_unflags = -std=gnu++11 -std=gnu++14 -std=c++11 -std=c++14
build_flags = 
	-std=gnu++17
	-D TARGET_THMI
	-D BOARD_HAS_PSRAM
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D LV_CONF_INCLUDE_SIMPLE
	-D BELL_DISABLE_FMT=1
	-I src
lib_deps = 
	${env.lib_deps}
	lvgl/lvgl @ 8.3.11
	https://github.com/liangyingy/arduino_xpt2046_library.git
	nanopb/Nanopb @ 0.4.8
	rweather/Crypto@^0.4.0
	einararnason/ArduinoQueue@^1.2.5

[env:s3mini]
board = esp32-s3-devkitc-1
board_build.flash_mode = dio
build_flags = 
	-D TARGET_S3MINI
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	${env.lib_deps}
	olikraus/U8g2 @ 2.35.7
	rweather/Crypto@^0.4.0
	einararnason/ArduinoQueue@^1.2.5
